version: "2.19"
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
  s3:
    build:
      context: ./s3_service
      dockerfile: dockerfile
    env_file:
      - .env
    networks:
      - default
    ports:
      - "8081:8081"
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    networks:
      - default
    ports:
      - "8082:80"
volumes:
  data: