FROM golang:latest

RUN mkdir /app

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

ENV AWS_CONFIG_FILE=/app/aws/config
ENV PATH="/app/aws:$PATH"

RUN go build -o /s3_service

EXPOSE 443

CMD [ "/s3_service" ]